### ISSUE TITLE
Expose ignition::msgs::Contact through ROS 2 msgs

### ISSUE THREAD

**Issue by vatanaksoytezer** [gazebosim/ros_gz#174]
Contact sensors are working nicely in Ignition through `ignition::msgs::Contact`. But they are not exposed through ros_ign. 

I don't mind adding another conversion to the `ros_ign_bridge`, but I am not %100 sure what ROS message type I should use. I couldn't fit this to any existing ROS2 message. I can of course define a custom message type or create a new message package (ala [gazebo_msgs](https://github.com/ros-simulation/gazebo_ros_pkgs)), but I just want this to be mergeable contribution, so this issue is to discuss what you would be happy to do. Let me know which option would be better to expose this and I will be happy to implement it @chapulina.

For reference `ignition::msgs::Contact` has type:

```
header {
  stamp {
    sec: 6
    nsec: 884000000
  }
}
contact {
  header {
    stamp {
      sec: 6
      nsec: 884000000
    }
  }
  collision1 {
    id: 96
  }
  collision2 {
    id: 7
  }
  position {
    x: -0.38790994410051866
    y: -0.21047000000004118
    z: -3.3862761483760551e-09
  }
  position {
    x: -0.38790994409679119
    y: -0.15047000000004118
    z: -3.4019649319816381e-09
  }
}

```

**Comment by chapulina** [comment]
> define a custom message type or create a new message package (ala gazebo_msgs),

Ohh have you seen the ones recently added in https://github.com/ignitionrobotics/ros_ign/pull/152?

**Comment by vatanaksoytezer** [comment]
> Ohh have you seen the ones recently added in #152?

Oh, those look neat! Will send a PR soon for bridge and hopefully close this after it gets merged! Thanks!
