### ISSUE TITLE
ros_ign_gazebo create.cpp usage message incorrect

### ISSUE THREAD

**Issue by oldtopos** [gazebosim/ros_gz#190]
and misleading

## Environment
* OS Version: Ubuntu 20.04
* Source build, ros2 branch

## Description
* Expected behavior: 
* 
* gflags::SetUsageMessage(
    R"(Usage: create -world [arg] [-file FILE] [-param PARAM] [-topic TOPIC]
                       [-string STRING] [-name NAME] [-x X] [-y Y] [-z Z]
                       [-R ROLL] [-P PITCH] [-Y YAW])");
* Actual behavior:   
* 
* gflags::SetUsageMessage(
    R"(Usage: create -world [arg] [-file FILE] [-param PARAM] [-topic TOPIC]
                       [-string STRING] [-name NAME] [-X X] [-Y Y] [-Z Z]
                       [-Roll ROLL] [-Pitch PITCH] [-Yaw YAW])");

**Comment by chapulina** [comment]
Oops, that's here:

https://github.com/ignitionrobotics/ros_ign/blob/5d9cfef3d58948a77b962d231e281c88ea88e188/ros_ign_gazebo/src/create.cpp#L51

**Comment by Aryaman22102002** [comment]
I have tried to fix this issue. Can someone please take a look at the pull request.  Link to pr: https://github.com/ignitionrobotics/ros_ign/pull/206

**Comment by Aryaman22102002** [comment]
Does this issue needs to be resolved for other branches too?

**Comment by chapulina** [comment]
> Does this issue needs to be resolved for other branches too?

Yeah I think so. If you could open a PR for `foxy`, we can then forward-port it to `galactic`. Thanks!

**Comment by chapulina** [comment]
Thanks @Aryaman22102002
