### ISSUE TITLE
NavSat Ignition Gazebo ROS Bridge Update 

### ISSUE THREAD

**Issue by jugpanther** [gazebosim/ros_gz#218]
Hello, 

I am curious if anyone has been working on getting the NavSat/GPS parameter in Ignition Gazebo converted with the ign_ros bridge. Using Citadel I was able to get the NavSat Ignition Gazebo sensor message to work, but I didn't see the ROS message conversion available in the sensor list. Any tips on how I can get the GPS sensor message converted to ROS.

**Comment by ahcorde** [comment]
Hi @jugpanther,

Just in case you want to go ahead and add this feature I drop here some tips:

 - Create the headers [here](https://github.com/ignitionrobotics/ros_ign/blob/melodic/ros_ign_bridge/include/ros_ign_bridge/convert.hpp) for the convertion functions IGN->ROS and ROS->IGN 
 - Implement [here](https://github.com/ignitionrobotics/ros_ign/blob/melodic/ros_ign_bridge/src/convert.cpp) the convertions 
 - Add [here](https://github.com/ignitionrobotics/ros_ign/blob/melodic/ros_ign_bridge/src/factories.hpp) the header for the factory 
 - Implement [here](https://github.com/ignitionrobotics/ros_ign/blob/melodic/ros_ign_bridge/src/factories.cpp) the factory method
 - And finally add an entry in the `get_factory_impl` in the factory.cpp file

Tips are the some for ROS or ROS 2. You should use the right APIs.

Add me as a reviewer if you create a PR

**Comment by jugpanther** [comment]
@ahcorde, 

Thank you for the tips. I will see what I can do.
