### ISSUE TITLE
ROS2 galactic, ign fortress, find_package(geometry_msgs REQUIRED)

### ISSUE THREAD

**Issue by ymei** [gazebosim/ros_gz#220]
I found that in order to compile (`colcon build`) successfully on ROS2, `ros_ign_gazebo/CMakeLists.txt` needs to be modified:

```
find_package(geometry_msgs REQUIRED)
ament_target_dependencies(create
  rclcpp
  ignition-math6
  geometry_msgs
)
```
Otherwise, it results in a linking error:
```
undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<std_msgs::msg::String_<std::allocator<void> > >()'
```

**Comment by chapulina** [comment]
What branch are you on? And what ROS version are you using?

**Comment by ymei** [comment]
branch: ros2
ROS2 version: galactic
ignition version: fortress

**Comment by chapulina** [comment]
Please use the `galactic` branch with Galactic. See the README for the version and branch combinations. I'll close this ticket for now, but please come back here if that doesn't solve the problem for you.

**Comment by ymei** [comment]
The `galactic` branch has the same problem.  It needs the same modification to compile for me.

**Comment by chapulina** [comment]
I just re-ran our CI and it compiled fine. I wonder what's different on your setup.

https://github.com/ignitionrobotics/ros_ign/runs/5428022992?check_suite_focus=true

**Comment by ymei** [comment]
Any information I can provide to help debug this?  Please let me know.  I'm no expert.  I got the idea to add `geometry_msgs` to solve my problem from this page: https://answers.ros.org/question/315023/ros2-debugging-techniques/

**Comment by chapulina** [comment]
Hi @ymei , I just looked more closely into this now. The `create` executable doesn't use `geometry_msgs`. If anything, we should link against `std_msgs`. How about you open a PR with that change and we see if CI passes? I think that would be ok, even if it looks like it's not strictly needed.

**Comment by chapulina** [comment]
`std::msgs` added to the `ros2` branch in https://github.com/gazebosim/ros_gz/pull/242
