### ISSUE TITLE
README from ros_ign_bridge Example 2 issue

### ISSUE THREAD

**Issue by joe28965** [gazebosim/ros_gz#236]
## Desired behavior
I was trying [Example 2 in the README](https://github.com/ignitionrobotics/ros_ign/tree/ros2/ros_ign_bridge#example-2-run-the-bridge-and-exchange-images) and I initially didn't get any images. I was trying and trying to see what I did wrong, only to realize I hadn't pressed play yet in Ignition.

Now, maybe I'm the idiot here. However, since it's an example that is linked in the ros2 integration tutorial (so it could attract newbies like me), would it be smart to add a `(don't forget to press play)` reminder somewhere?

## Implementation suggestion
Perhaps it would be wise to change the line in example 2 from:

> First we start Ignition Gazebo.

To:

> First we start Ignition Gazebo (don't forget to hit play, or Ignition Gazebo won't generate any images).

## Additional context
If I'm the idiot here and it's just me, then feel free to close this issue. If it's a good idea, let me know and I'll make a PR for it.

**Comment by mjcarroll** [comment]
I think that's a reasonable enhancement to the docs.  Always better to be explicit to save people some confusion.

Feel free to open a PR, I'd be happy to review it.
