### ISSUE TITLE
robot_publisher.launch tf joint_publisher in ros noetic ign cital

### ISSUE THREAD

**Issue by xzjohy** [gazebosim/ros_gz#247]
pls help me how to edit robot_publisher.launch tf joint_publisher in ros noetic ign cital

**Comment by chapulina** [comment]
Hi @xzjohy  , please direct questions to https://answers.gazebosim.org/. This issue tracker is for bug reports and feature requests.

And also please use the issue template next time.

See you at Gazebo Answers.
