### ISSUE TITLE
NavSatFix bridge on ROS2 Galactic

### ISSUE THREAD

**Issue by Marcelomm103** [gazebosim/ros_gz#267]
## Desired behavior

Hey you all!

I would like to know if NavSatFix bridge is going to be ported to ROS2 Galactic as well as it was to ROS1 Melodic. I'm in dire need of it, if someone could help me would be great!

## Implementation suggestion

NavSatFix ros_bridge in ROS2 Galactic

**Comment by mjcarroll** [comment]
Close by #268

**Comment by Marcelomm103** [comment]
Thank you!

May i point out that there is an error in the readme of the ign bridge, is NavSatFixed and you implemented NavSatFix.
