### ISSUE TITLE
Missing dependencies for ros_ign_gazebo_demos

### ISSUE THREAD

**Issue by rsinnet** [gazebosim/ros_gz#276]
## Environment
* OS Version: All
* Source or binary build? All

## Description
* Expected behavior: rosdep install should install all necessary packages to run the demos
* Actual behavior: rosdep install completes but some unlisted dependencies are missing

## Steps to reproduce
1. Install minimal version of ROS.
2. Clone this repo into a new catkin workspace
3. Run rosdep install
4. Run roslaunch on pretty much any demo

**Comment by chapulina** [comment]
* https://github.com/gazebosim/ros_gz/pull/277
