### ISSUE TITLE
0.244.8-1 fails to build on the Humble Buildfarm

### ISSUE THREAD

**Issue by audrow** [gazebosim/ros_gz#324]
Here's the reverted PR:
https://github.com/ros/rosdistro/pull/35128

**Comment by mjcarroll** [comment]
Should be fixed by https://github.com/gazebosim/ros_gz/pull/317, but requires another release.

**Comment by mjcarroll** [comment]
https://github.com/ros/rosdistro/pull/35179

**Comment by mjcarroll** [comment]
0.244.9 successfully builds: https://build.ros2.org/job/Hbin_uJ64__ros_gz__ubuntu_jammy_amd64__binary/9/
