### ISSUE TITLE
Get pose array with link name

### ISSUE THREAD

**Issue by Rezenders** [gazebosim/ros_gz#330]
## Desired behavior
It would be nice to be able to bridge the gz topic ` /world/empty/pose/info` to ROS2 as position array including the name of the links. As described in this [question](https://answers.gazebosim.org/question/27215/ground-truth-of-ignition-gazebo-model-through-ros/).

As far as I understood, now it is only possible to bridge `gz.msgs.Pose_V` to `geometry_msgs/PoseArray` which doesn't include the link name

**Comment by azeey** [comment]
I've given an [answer](https://answers.gazebosim.org/question/27215/ground-truth-of-ignition-gazebo-model-through-ros/?answer=28552#post-id-28552) to the question you mentioned. Since there's already a way to do this, I'll go ahead and close this. Feel free to open if that is not the case.
