### ISSUE TITLE
hi i was trying to export an urdf that contains meshes to ignition fortress but i couldn't, anyone can help me please 

### ISSUE THREAD

**Issue by jsvsebastian** [gazebosim/ros_gz#334]
## Environment
* OS Version: 
* Source or binary build?
  
  

## Description
* Expected behavior: 
* Actual behavior: 

## Steps to reproduce

1.
2.
3.

**Comment by ahcorde** [comment]
Hi @jsvsebastian, 

we can't help you without providing more information, anyhow this kind of question which are not bug related you should [ask them here](https://robotics.stackexchange.com/).

Feel free to open the question there with more information, post the link here and I will be happy to answer.

Closing this for now
