### ISSUE TITLE
ros_gz_bridge with bidirectional /clock topic will not forward any messages to ROS2

### ISSUE THREAD

**Issue by jhierck-riwo** [gazebosim/ros_gz#341]
## Environment
* OS Version: Ubuntu 22.04
* ROS2: Humble
* Gazebo: Fortress (6.13.0) (binary)
* ros_gz_bridge: `ros-humble-ros-gz-bridge/jammy,now 0.244.9-1jammy.20221207.034850` (binary)
* ros_gz: `ros-humble-ros-gz/jammy 0.244.9-1jammy.20221207.081709` (binary)

## Description
* Expected behavior: When I create a bidirectional clock (launch file snippet below), I expect the `/clock` topic in ROS2 to publish the Ignition clock properly.
* Actual behavior: When I create a bidirectional clock, nothing is published on the `/clock` topic in ROS2. In Ignition, two clock topics are created: `/clock` and `/world/<worldname>/clock`. Only `/world/<worldname>/clock` publishes actual time, but this Ignition topic is not bridged to ROS2. The Ignition topic `/clock` is bridged to ROS2 but does not contain any data.

```python
bridge = Node(
    package='ros_gz_bridge',
    executable='parameter_bridge',
    arguments=[
        '/clock@rosgraph_msgs/msg/Clock@ignition.msgs.Clock',  # Does not work
        '/clock@rosgraph_msgs/msg/Clock[ignition.msgs.Clock',  # Works fine
    ],
    output='screen'
)
```

Interestingly enough, when the unidirectional clock is used, both `/clock` and `/world/<worldname>/clock` publish data when viewed using `ign topic --echo --topic /clock` and  `ign topic --echo --topic /world/empty/clock`.

When using the bidirectional clock, only `ign topic --echo --topic /world/empty/clock` publishes data, `ign topic --echo --topic /clock` is empty.

This is of course an easy fix, just replace any  `'/clock@rosgraph_msgs/msg/Clock@ignition.msgs.Clock'` with `'/clock@rosgraph_msgs/msg/Clock[ignition.msgs.Clock'`. But this behavior is a little unexpected so it might be useful to mention this somewhere in documentation or a warning message in the `ros_gz_bridge` node.

**Comment by mjcarroll** [comment]
I believe this is an interaction with this bit of logic: https://github.com/gazebosim/gz-sim/blob/31f7d5b384408eb88db3fcc85cc5529eb926f069/src/SimulationRunner.cc#L705-L732

If during startup, gazebo detects that there is another publisher on `/clock`, it will only create the fully qualified `/world/<worldname>/clock` topic.

This was introduced quite a while ago with the assumption that gazebo would be the only `/clock` publisher, the sole source of clock information.  It was helpful if you were running multiple instances without clobbering each other.

I agree that the documentation should be a bit clearer though.  Gazebo itself will emit a log message if this condition is met, but maybe the bridge should as well?

**Comment by ahcorde** [comment]
Added documentation here https://github.com/gazebosim/ros_gz/pull/393, hope this help
