### ISSUE TITLE
When parameter_bridge receives a SIGINT, it waits until it receives SIGINT again.

### ISSUE THREAD

**Issue by ymd-stella** [gazebosim/ros_gz#345]
## Environment
* OS Version: osrf/ros:humble-desktop-full (host OS=Ubuntu 20.04.5)
* binary build: 0.244.9

## Description
* Expected behavior: parameter_bridge terminates when SIGINT is received.
* Actual behavior: When parameter_bridge receives a SIGINT, it waits until it receives it again.

I think `gz::transport::waitForShutdown()` is not needed.

https://github.com/gazebosim/ros_gz/blob/1271a5a59bac5899990a8b0e00b1dcd1582c1582/ros_gz_bridge/src/parameter_bridge.cpp#L172-L176

## Steps to reproduce

1. Execute `ros2 run ros_gz_bridge parameter_bridge` with any args
2. Press `Ctrl + c`. Then message `[INFO] [xxx] [rclcpp]: signal_handler(signum=2)` is printed out.
3. Press `Ctrl + c` again. Then, the process is terminated.

**Comment by azeey** [comment]
I think you're correct.  The `gz::transport::waitForShutdown` can be removed. Do you mind creating a PR with that change?
