### ISSUE TITLE
ros_gz_bridge parameter_bridge not parsing yaml files to create parameter bridges.

### ISSUE THREAD

**Issue by Jack17432** [gazebosim/ros_gz#354]
## Environment
* OS Version: Ubuntu 22.04
* ROS2 version: humble
* Source: 6c2e56efbaadf6e3683d7817703b1b626b768726, ros2

## Description
* Expected behavior: ros_gz_bridge parses YAML file to load up a list of bridges
* Actual behavior: [readFromYaml]: Could not parse config, top level must be a YAML sequence

## Steps to reproduce

1. download **any** of the yaml examples in the ros_gz_bridge example files
2. Use parameter_bridge from ros_gz_bridge use pass in 'config_file': path_to_config
3. Run ros2 launch file

## Output
![image](https://user-images.githubusercontent.com/44985312/214157355-ad0a78da-0882-44c1-ba38-f9ef11ee5c4a.png)
![image](https://user-images.githubusercontent.com/44985312/214157225-a605045a-8ff2-4323-865d-8f81c870ebbd.png)

**Comment by mjcarroll** [comment]
Thanks for reporting, taking a look

**Comment by mjcarroll** [comment]
What happens if you run from command line, for example:

```
ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=./src/ros_gz/ros_gz_bridge/test/config/full.yaml
```

**Comment by Jack17432** [comment]
![image](https://user-images.githubusercontent.com/44985312/214177383-4e687932-86ac-4406-ae2e-0c816db8bee8.png)

**Comment by mjcarroll** [comment]
Okay, this indicates that it can find this file when loaded from the command line.  I believe the error you are seeing is because the configuration is pointing to a file that does not exist.

I'm going to open a PR to make the error condition more explicit when you are trying to open a non-existent file.

The failure to load with `ignition.` prefixed messages is a second fix that I will need to add to maintain compatibility with the `humble` branch.

**Comment by mjcarroll** [comment]
@Jack17432 friendly ping, can you confirm that you were able to get this working with the improved error messages?

**Comment by ghost** [comment]
Hi @mjcarroll, I've encountered the same error trying to run a yaml file : 

```
~$ ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=~/gazebo_ws/ros_bridge/config.yaml
[ERROR] [1687567401.137092983] [readFromYaml]: Could not parse config, top level must be a YAML sequence
[ERROR] [1687567402.136611339] [readFromYaml]: Could not parse config, top level must be a YAML sequence
```
I added the 'improved error messages" changes you made, to no effect.

the contents of config.yaml are just : 

```
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10       # Default 10
  publisher_queue: 10        # Default 10
  lazy: false                # Default "false"
  direction: GZ_TO_ROS       # Default "BIDIRECTIONAL" - Bridge both directions
                             # "GZ_TO_ROS" - Bridge GZ topic to ROS
                             # "ROS_TO_GZ" - Bridge ROS topic to GZ
```
Am I supposed to place that yaml file somewhere in particular?

**Comment by azeey** [comment]
Doesn't the `GZ_TO_ROS` need to be in quotes?

**Comment by TanguyGerniers** [comment]
> Hi @azeey, thank you for your reply. GZ_TO_ROS isnt in quotes in Jack's .yaml further up nor in the [example code for the ros_gz_bridge](https://github.com/gazebosim/ros_gz/blob/humble/ros_gz_bridge/README.md) and the [test configs](https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_bridge/test/config/full.yaml), but I have tried doing so just in case, with the same outcome.

**Comment by mjcarroll** [comment]
Correct, "GZ_TO_ROS" should be in quotes.

**Comment by mjcarroll** [comment]
@Jack17432 since you haven't replied in some time, I'm going to close this out.  Feel free to re-open or open a new issue if you have more troubles.

**Comment by Ali-Hossam** [comment]
If anyone happens to encounter the same error, make sure that you added the config folder that has the yaml file to CMakeLists install Directory.

**Comment by MnM03** [comment]
Did someone solved this issue? I am having the same problem.

**Comment by anushkav1888** [comment]
I was running parameter bridge node using a YAML config file through a python launch file, and encountered the same error.
Make sure your config exists in install directory inside your workspace, and you define config file path correctly in your launch file (specify using get_package_share_directory or any other equivalents) .

**Comment by simona-99** [comment]
Hi,
I'm also getting the same error: ` [readFromYaml]: Could not parse config, top level must be a YAML sequence`
And when I run this: 
```
ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=./src/ros_gz/ros_gz_bridge/test/config/full.yaml
[ERROR] [1727164413.215385465] [readFromYaml]: Could not parse config, top level must be a YAML sequence
```
I made sure to include the config folder containing the .yaml file in the CMakeLists.txt file:
```
install(DIRECTORY config/
  DESTINATION share/${PROJECT_NAME}/config
)
```
I also made sure that the config file exists in the install directory inside my workspace. 

Thank you in advance for any help you can give me ;)

**Comment by Kmedrano101** [comment]
As @Ali-Hossam and @anushkav1888  mentioned, solution is to make sure that the folder where your yaml file is be included into CMakeLists.txt : install(DIRECTORY config DESTINATION share/${PROJECT_NAME}) foy pyhon setup: data_files=[(os.path.join('share', package_name, 'resource'), glob('config/*.yaml'))]. Tested in Ubuntu 22.04, ROS2 humble.
