### ISSUE TITLE
convert gz.msgs.Wrench to geometry_msgs/WrenchStamped instead of geometry_msgs/Wrench

### ISSUE THREAD

**Issue by xibeisiber** [gazebosim/ros_gz#359]
## Desired behavior
The timestamp and frame information contained in` gz.msgs.Wrench` is dropped when converting to `geometry_msgs/Wrench`.
Maybe use ` geometry_msgs/WrenchStamped`?

## Implementation suggestion
convert `gz.msgs.Wrench `to `geometry_msgs/WrenchStamped` instead of `geometry_msgs/Wrench`

**Comment by azeey** [comment]
I think we can add `geometry_msgs/WrenchStamped` as an additional output type for `gz.msgs.Wrench`. Would you be able to create a PR?

**Comment by azeey** [comment]
Actually, looks like there's already a PR for that https://github.com/gazebosim/ros_gz/pull/327

**Comment by azeey** [comment]
#327 has been merged.
