### ISSUE TITLE
Colcon build failure for Gazebo garden with ROS humble

### ISSUE THREAD

**Issue by himanshu1196** [gazebosim/ros_gz#361]
## Environment
* OS Version: Ubuntu 22.04
* ROS humble binary
* Source build, branch - humble 

## Description
* Expected behavior: colcon build to succeed for all packages
* Actual behavior: ros_gz_interfaces package fails due to 'pathlib' module not being available

## Steps to reproduce

1. mkdir -p ~/vrx_ws/src
2. cd ~/vrx_ws/src
3. git clone https://github.com/gazebosim/ros_gz.git -b humble
4. cd ~/vrx_ws
5. GZ_VERSION=garden colcon build

## Output

> GZ_VERSION=garden colcon build

> Starting >>> ros_gz_interfaces

> Starting >>> ros_gz_sim

> Starting >>> vrx_gazebo

> Finished <<< vrx_gazebo [1.35s]                                                             
     
> Starting >>> wamv_description

> Finished <<< wamv_description [1.14s]                                                            

> Starting >>> wamv_gazebo

> Finished <<< wamv_gazebo [1.32s]                                                                    

> --- stderr: ros_gz_interfaces 
                                                                    
> Traceback (most recent call last):

>   File "/opt/ros/humble/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 8, in  <module>

>     from rosidl_generator_py import generate_py

>   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_py/__init__.py", line 18, in <module>

>     from .import_type_support_impl import import_type_support

>   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_py/import_type_support_impl.py", line 17, in <module>

>     from rpyutils import add_dll_directories_from_env

>   File "/opt/ros/humble/lib/python3.10/site-packages/rpyutils/__init__.py", line 16, in <module>

>     from .import_c_library import import_c_library

>   File "/opt/ros/humble/lib/python3.10/site-packages/rpyutils/import_c_library.py", line 17, in <module>

>     from pathlib import Path

> ModuleNotFoundError: No module named 'pathlib'

> gmake[2]: *** [ros_gz_interfaces__py/CMakeFiles/ros_gz_interfaces__py.dir/build.make:224: 
rosidl_generator_py/ros_gz_interfaces/_ros_gz_interfaces_s.ep.rosidl_typesupport_fastrtps_c.c] Error 1

> gmake[1]: *** [CMakeFiles/Makefile2:590: ros_gz_interfaces__py/CMakeFiles/ros_gz_interfaces__py.dir/all] Error 2

> gmake: *** [Makefile:146: all] Error 2

> ---

> Failed   <<< ros_gz_interfaces [24.5s, exited with code 2]

> Aborted  <<< ros_gz_sim [28.7s]                                   

> Summary: 3 packages finished [28.9s]

>   1 package failed: ros_gz_interfaces

>   1 package aborted: ros_gz_sim

>   2 packages had stderr output: ros_gz_interfaces ros_gz_sim

>   12 packages not processed

The pathlib module should be available in python3.4+. Is there an environment variable which needs to be set before I run the colcon build?

**Comment by azeey** [comment]
Not sure if things have been updated since you created the issue, but I am not able to reproduce this locally. The build succeeds without any issues for me.

**Comment by azeey** [comment]
@himanshu1196, have you had a chance to try it again?

**Comment by himanshu1196** [comment]
> @himanshu1196, have you had a chance to try it again?

Thank you for responding @azeey. I was able to build it successfully in a new workspace finally. Although I am still not sure what caused the reported behavior.
