### ISSUE TITLE
Memory Leak using ros_gz_bridge to convert LaserScan

### ISSUE THREAD

**Issue by retinfai** [gazebosim/ros_gz#366]
## Environment
* OS Version: Ubuntu 22.04 LTS
* Source or binary build?
Source Build: `ros2` branch, `commit e7660f8`

### Expected behavior:
Potential Memory Leak

### Actual behavior:
Adding Lidar to the `ros_gz_bridge`, results in `gz sim server` consuming memory, going from 2% memory usage to 28.4% memory usage after running for over 10 minutes (this is repeatable)

## Steps to reproduce

1. `gz sim gpu_lidar_sensor.sdf`
2. `ros2 run ros_gz_bridge parameter_bridge /lidar@sensor_msgs/msg/LaserScan@gz.msgs.LaserScan`
3. Let it run for over 10 Minutes

## Output
**Note:** process `3978322` is the `gz sim server` process
![Screenshot from 2023-03-01 12-16-08](https://user-images.githubusercontent.com/79831813/222004878-5e67ff25-2d95-414b-8cf4-c0ea4dc69b67.png)

For comparison, here is the same simulation after just restarting.
![Screenshot from 2023-03-01 12-16-44](https://user-images.githubusercontent.com/79831813/222005116-9d18c05c-0874-4160-9fdb-0b0375d52ef9.png)

**Comment by retinfai** [comment]
After more than an hour of running:
![Screenshot from 2023-03-01 14-32-22](https://user-images.githubusercontent.com/79831813/222022188-d5998dc4-f587-4a6c-8be0-f118a714c093.png)

**Comment by mjcarroll** [comment]
I think this is likely unrelated to the bridge itself.  The two ruby instances are going to be the gazebo server and gazebo gui.  To help track this down, can you verify which of the two that it is, and we can get it moved to the appropriate issue tracker.

**Comment by retinfai** [comment]
Sweet, the process that's eating up the memory  - `process 10432` in the last image posted - is `gz sim server`. I'll re run the test without the bridge to confirm.

**Comment by retinfai** [comment]
Another Update:
Left running for several hours with no memory leak, no `param` bridge:
![Screenshot from 2023-03-01 19-06-07](https://user-images.githubusercontent.com/79831813/222059518-4a502e56-d617-4d22-b63e-a1e6e2bcdb66.png)

However, after **turning on** visualise lidar, the memory problem stated before has arisen over **minutes**
![Screenshot from 2023-03-01 19-14-52](https://user-images.githubusercontent.com/79831813/222060530-88561563-002a-4d46-934e-6bb18399a3c0.png)

**Comment by retinfai** [comment]
To redefine the problem more specifically:

Memory problems (possible leakage) occur when **visualising the lidar** *or* there is a `parameter_bridge` converting `gz.msg.LaserScan` to `sensor_msgs/msgs/LaserScan`. 

*Note:* I retested with **no** visualise lidar but **with** a param bridge - this lead to memory leakage

**Comment by mjcarroll** [comment]
I think it's likely that the Lidar doesn't do anything unless there are active subscribers.  Either the GUI or parameter_bridge will trigger it to start processing.  I'm going to transfer this issue to gz-sensors, as that is likely where the issue resides.

**Comment by iche033** [comment]
Is this in Garden? We fixed a lidar memory leak issue in gz-rendering7 (Garden) not long ago. Maybe we just need to do another gz-rendering7 release: https://github.com/gazebosim/gz-rendering/pull/799

**Comment by retinfai** [comment]
Yes we are using Garden. Ahh yep, that's exactly the issue thanks. I'm going to close this issue.

To receive the update, how do I go about doing this. Do I just redo the binary install, or do I source install?

**Comment by iche033** [comment]
we'll need to make an gz-rendering release on our end. Once that's out, you should only just need to do a binary install to get the latest version.

**Comment by iche033** [comment]
gz-rendering 7.3.0 has been released.

**Comment by paoloelle** [comment]
@iche033 do you know if this problem exists in Gazebo Fortress?

**Comment by iche033** [comment]
I don't think so. The mem leak was from code added in Garden.
