### ISSUE TITLE
NavSat Topic Conversion Not Supported in ROS 2 Gazebo Bridge (Fortress)

### ISSUE THREAD

**Issue by Onicc** [gazebosim/ros_gz#433]
## Environment
* OS Version:  Ubuntu 22.04
* ROS 2 Version: Humble
* Gazebo Version: Fortress
* Branch: https://github.com/gazebosim/ros_gz/tree/humble

## Description
I am trying to convert the NavSat topic from ign gazebo to the NavSat topic in ROS 2. However, I have noticed that the bridge in the Fortress version does not support the conversion of NavSat topics. Below are the results of my execution:
```
$ ros2 run ros_gz_bridge parameter_bridge /navsat1@sensor_msgs/msg/NavSatFixed[ignition.msgs.NavSat
[INFO] [1688995893.840111512] [ros_gz_bridge]: Creating GZ->ROS Bridge: [/navsat1 (ignition.msgs.NavSat) -> /navsat1 (sensor_msgs/msg/NavSatFixed)] (Lazy 0)
[WARN] [1688995893.840240258] [ros_gz_bridge]: Failed to create a bridge for topic [/navsat1] with ROS2 type [sensor_msgs/msg/NavSatFixed] to topic [/navsat1] with Gazebo Transport type [ignition.msgs.NavSat]
```

## Investigation
I have found that the `humble` branch includes `ros_gz` and `ros_ign`, but only `ros_gz` contains [navsat.launch.py](https://github.com/gazebosim/ros_gz/blob/humble/ros_gz_sim_demos/launch/navsat.launch.py). It seems that `ros_ign` does not support the conversion of NavSat topics.

**Comment by mjcarroll** [comment]
```
$ ros2 run ros_gz_bridge parameter_bridge /navsat1@sensor_msgs/msg/NavSatFixed[ignition.msgs.NavSat
```

The ROS message is `sensor_msgs/msg/NavSatFix`.  The error message could probably be a bit more informative in this case, but that will get it working for you.

**Comment by Onicc** [comment]
You're absolutely right! Thank you for pointing out that the ROS message is `sensor_msgs/msg/NavSatFix`. Your input is much appreciated!
