### ISSUE TITLE
Make gazebo garden to use ros2 wall time instead of sim time along with ackermann steering plugin and ground truth odometry outputs 

### ISSUE THREAD

**Issue by Rak-r** [gazebosim/ros_gz#445]
## Environment
* OS Version: Ubuntu 22.04
* Source 
  Gazebo garden 
  Humble branch

## Description
* Expected behavior: Gazebo should publish messages from the Ackermann steering plugin and ground truth odometry on ros2 wall time instead of sim time

Could anybody advice on this?

**Comment by azeey** [comment]
In general, I believe it's expected for Gazebo to publish in sim time and ROS 2 to use sim time by setting the ROS 2 parameter `use_sim_time = true`. Have you tried that?
