### ISSUE TITLE
2D Bounding Box messages from bounding box cameras are not bridged

### ISSUE THREAD

**Issue by wittenator** [gazebosim/ros_gz#457]
## Desired behavior
There should be a bridge for the translation of 2D BBox messages coming from bounding box cameras.

## Alternatives considered
None

## Implementation suggestion
The corresponding ignition messages should be added. I did this in https://github.com/wittenator/ros_gz/tree/humble .

## Additional context
This is useful if one wants to replace e.g. an object detection node that runs on CUDA-hardware only with a Gazebo bounding box camera to make the simulation run on any hardware.

**Comment by wittenator** [comment]
@ahcorde Is the port to ROS Iron something the Ros_gz team will do or should I do another PR?

**Comment by ahcorde** [comment]
@wittenator, if you want to take care of the forward port I really appreciate it otherwise I will do it this or next week.

**Comment by wittenator** [comment]
Sure, I don't mind doing that. I'll probably come around to it on Monday tho

**Comment by wittenator** [comment]
Ahh, do you know when to expect the changes reflected in the binary packages?

**Comment by ahcorde** [comment]
I can make a release today, and changes will be available in the next humble sync.

**Comment by wittenator** [comment]
The humble release is not urgent for me anymore, I switched to Iron in the meantime^^ I was just curious, but thanks for the info!

**Comment by wittenator** [comment]
I added a PR to the Iron branch with the cherry-picked changes from the last merged PR in #460 .

**Comment by mjcarroll** [comment]
@ahcorde to close after rolling release

**Comment by ahcorde** [comment]
PR was forward ported to `rolling` too https://github.com/gazebosim/ros_gz/pull/466. 

Closed. Thank you @wittenator for your contributions.
