### ISSUE TITLE
Make `ros_gz_sim::create` use ROS parameters

### ISSUE THREAD

**Issue by mjcarroll** [gazebosim/ros_gz#459]
Currently, the `ros_gz_sim::create` node uses gflags to configure where and how models are loaded.

For maximum compatibility with ROS, I think it makes sense to switch the gflags arguments to use rclcpp::Parameters.

**Comment by yaswanth1701** [comment]
So, one should add XYZ and RPY as rosparams right? or all the gflag arguments ?

**Comment by ahcorde** [comment]
Hi @yaswanth1701, all the gflags arguments

**Comment by Ayush1285** [comment]
There is a gflag argument 'param', which allows us to pass any ros parameters which is not declared in the create.cpp file. So, now that we are converting gflag arguments to Parameters itself, we will lose this functionality, right?

**Comment by Ayush1285** [comment]
@mjcarroll any comments?

**Comment by mjcarroll** [comment]
@Ayush1285 In my opinion, since this is currently primarily used from ROS launch files, it would make sense to port all available parameters to be ROS parameters.  In the case that no ROS parameter arguments are available, we can revert to the `gflags` behavior.  I think preserving behavior is also important for the existing launch files that are out there.

An alternative to the gflags "fallback" parsing is to provide two separate executables, one exclusively gflags and one exclusively ROS paramaters, but I think that would result in a good bit of duplication.  I'll leave that up to whoever implements it to see which way works better.

I'm envisioning getting us positioned to take advantage of custom launch actions down the road, so the more "native" ROS support we have, the better.

**Comment by Ayush1285** [comment]
I'm thinking about implementing this. I'll go with the first behaviour.
