### ISSUE TITLE
ros_gz for humble/harmonic 

### ISSUE THREAD

**Issue by 0mnimon** [gazebosim/ros_gz#461]
As per gazebosim doc it is mentioned that you can download ros_gz for humble/harmonic using "ros-humble-ros-gzharmonic"
I tried both prerelease and released repo but both are providing error that "the command does not exist"
How do I get ros_gz for humble/harmonic?

![image](https://github.com/gazebosim/ros_gz/assets/150802301/5c69c8dc-dab9-4652-9585-937f8f21abf5)

**Comment by azeey** [comment]
@0mnimon, thanks for the issue. It's an error in the documentation. Currently the Humble/Harmonic combination is not supported.

**Comment by azeey** [comment]
Fix: https://github.com/gazebosim/docs/pull/407

**Comment by 0mnimon** [comment]
@azeey Thank you for the reply, will the combination be available any time soon?

**Comment by azeey** [comment]
https://github.com/gazebosim/ros_gz/pull/462

**Comment by quantumxt** [comment]
Hi there, just wondering if there's a binary for `arm64` architecture? 

I compared the following Packages list:
- `amd64` (https://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/jammy/main/binary-amd64/) 
- `arm64` (https://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/jammy/main/binary-arm64/)

`ros-humble-ros-gzharmonic` was only listed inside `amd64`, but not `arm64`.
