### ISSUE TITLE
ROS2 topics are created but the echo is empty

### ISSUE THREAD

**Issue by mavneo** [gazebosim/ros_gz#464]
I'm currently running, Ubuntu 22.04, ROS2 Humble and Garden. I have tried the basic tutorial mentioned here about listening the keystrokes, https://gazebosim.org/docs/garden/ros2_integration. 
While I'm able to see the keyboard strokes data in gz topic -e -t (topic), I'm unable to see the keyboard strokes when I echo the ROS2. Although the ROS2 topic is created. 

Can anyone tell me where this is wrong, would really appreciate it.

Thanks

**Comment by biagio-trimarchi** [comment]
@mavneo 
Have you been able to solve this?
I am facing the same problem I think, with a different topic though. The topic subscription is created, but when I am echoing the messages on the topic I do not see any message.

I have posted the issue also on [Robotic Stack Exchange](https://robotics.stackexchange.com/questions/107827/ros-gz-bridge-does-not-publish-on-ros2-topic) and [Gazebo Community](https://community.gazebosim.org/t/ros-gz-bridge-does-not-publish-on-ros2-topic/2493).
