### ISSUE TITLE
`on_exit_shutdown` is not evaluated correctly

### ISSUE THREAD

**Issue by azeey** [gazebosim/ros_gz#494]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? 2dca3580f7ac27f954fcdffbcff956aba963076f

## Description
* Expected behavior: Setting `on_exit_shutdown` launch argument to false to work properly
* Actual behavior: `on_exit_shutdown` is a `str` when evaluated in the `if` statement below:
https://github.com/gazebosim/ros_gz/blob/2dca3580f7ac27f954fcdffbcff956aba963076f/ros_gz_sim/launch/gz_sim.launch.py.in#L58

This means setting it to `'true'` or `'false'` will always be treated as `True`. Perhaps we can use `IfCondition` and call `evaluate` here instead?

**Comment by Amronos** [comment]
This has been fixed in #617.
