### ISSUE TITLE
Backport IMU Covariances to ROS Iron

### ISSUE THREAD

**Issue by wittenator** [gazebosim/ros_gz#539]
## Desired behavior
I would like to also have covariance data in IMU messages in ROS Iron if I build the Iron branch from source.

## Alternatives considered
None

## Implementation suggestion
Would it be possible to backport the conditional covariance filling in IMU messages to the Iron branch?

**Comment by azeey** [comment]
I don't think there's a reason for not backporting it. Would you be able to open a PR?

**Comment by wittenator** [comment]
Sure thing, I created a PR for that.

**Comment by azeey** [comment]
Fixed by #375.
