### ISSUE TITLE
JointStates bridge failing for ROS2 Humble with Gazebo Garden

### ISSUE THREAD

**Issue by rokasgie** [gazebosim/ros_gz#558]
## Environment
* OS Version: e.g, Ubuntu 20.04
* Source or binary build?
  Source, humble branch, a348c07527c54f387a576413a3e3d6d7431ff45b

## Description
* Expected behavior: Successful message transfer
* Actual behavior: Warning of failure. When running Gazebo only the timestamp is visible and all other fields are empty.

## Steps to reproduce
1. `ros2 run ros_gz_bridge parameter_bridge /my/joint_states@std_msgs/msg/JointState@gz.msgs.Model`

## Output
`ros_gz_bridge]: Creating GZ->ROS Bridge: [/my/joint_states (gz.msgs.Model) -> /my/joint_states (std_msgs/msg/JointState)] (Lazy 0)
[WARN] [1717448826.963089241] [ros_gz_bridge]: Failed to create a bridge for topic [/my/joint_states] with ROS2 type [std_msgs/msg/JointState] to topic [/my/joint_states] with Gazebo Transport type [gz.msgs.Model]`

**Comment by azeey** [comment]
The `JointState` message is in `sensor_msgs` not `std_msgs`, so your command should be `ros2 run ros_gz_bridge parameter_bridge /my/joint_states@sensor_msgs/msg/JointState@gz.msgs.Model`. I'll go ahead and close this, but feel free to reopen if you still the issue.
