### ISSUE TITLE
`ros-humble-ros-gzharmonic` binary for ARM64 architecture

### ISSUE THREAD

**Issue by quantumxt** [gazebosim/ros_gz#614]
Hi there, just wondering if there's a binary for `arm64` architecture? 

I compared the following Packages list:
- `amd64` (https://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/jammy/main/binary-amd64/) 
- `arm64` (https://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/jammy/main/binary-arm64/)

`ros-humble-ros-gzharmonic` was only listed inside `amd64`, but not `arm64`.

**Comment by martincerven** [comment]
Hmm and I thought `E: Unable to locate package ros-humble-ros-gzharmonic` is due to wrong documentation  😓

**Comment by azeey** [comment]
Unfortunately, we do not provide binaries for ARM64 and there is currently no plan to do so. ROS Jazzy does have a version of Gazebo and ros_gz in ARM64, so I suggest upgrading.
