### ISSUE TITLE
Error in launch file using <ros_gz_bridge>

### ISSUE THREAD

**Issue by caguero** [gazebosim/ros_gz#650]
## Environment
* OS Version:  Ubuntu 24.04
* Source or binary build? Source
  
  

## Description

We might have broken something since #628 . If I run this launch file (saved as `ros_gz_bridge.launch`:

```xml
<launch>
  <ros_gz_bridge
    bridge_name="ros_gz_bridge"
    config_file="/home/caguero/ros_gz_ws/src/ros_gz/ros_gz_bridge/test/config/full.yaml"/>
</launch>
```

with:
```bash
ros2 launch ros_gz_bridge ros_gz_bridge.launch
```

I'm getting this error message:
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): value='False' is not an instance of <class 'bool'>
```

@Amronos, could you try this on your end to confirm please?

**Comment by Amronos** [comment]
> @Amronos, could you try this on your end to confirm please?

Does occur on my end too.
