### ISSUE TITLE
Port bridge tests to ROS 2

### ISSUE THREAD

**Issue by chapulina** [gazebosim/ros_gz#92]
When we initially ported `ros_ign_bridge` from ROS 1 to ROS 2, there wasn't an easy way to port the tests yet (I believe there was no launch testing). Now that's already available, so we should enable tests for ROS 2:

https://github.com/ignitionrobotics/ros_ign/blob/e2feecf0cbba07a2f2b630c3dd42a674d251bc61/ros_ign_bridge/CMakeLists.txt#L111-L113

**Comment by ahcorde** [comment]
PR https://github.com/ignitionrobotics/ros_ign/pull/98
